#
# Copyright © 2021, Ozone HIS <info@ozone-his.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

version: '3'
services:
  eip-client:
    container_name: kapsiki-eip-client
#    environment:
#        - EIP_PROFILE=dev
    env_file:
      - env/elis.env
    image: kapsiki-eip-client:latest
    ports:
      - "8088:8080"
    volumes:
      - /Users/njiddasalifu/workspace/kds/DI/eip-openelis-openmrs/openelis-openmrs/target/eip-openelis-openmrs-1.0.0-SNAPSHOT.jar:/eip-client/routes/eip-openelis-openmrs-1.0.0-SNAPSHOT.jar
